// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using carpoolmvc.Data;

namespace carpoolmvc.Migrations
{
    [DbContext(typeof(carpoolMvcDb))]
    [Migration("20240830014724_PrimeiraMigracao")]
    partial class PrimeiraMigracao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("carpoolmvc.Models.Caronas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Caronas");
                });

            modelBuilder.Entity("carpoolmvc.Models.Orçamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<double>("Abastecimento")
                        .HasColumnType("double");

                    b.Property<double>("Entrada")
                        .HasColumnType("double");

                    b.Property<double>("Ganhos")
                        .HasColumnType("double");

                    b.Property<double>("Gastos")
                        .HasColumnType("double");

                    b.Property<double>("Saida")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.ToTable("Orçamento");
                });
#pragma warning restore 612, 618
        }
    }
}
